/*******************************************************************************
 * Copyright (C) 2011 Atlas of Living Australia
 * All Rights Reserved.
 * 
 * The contents of this file are subject to the Mozilla Public
 * License Version 1.1 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.mozilla.org/MPL/
 * 
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 ******************************************************************************/
package au.org.ala.delta.slotfile;

import junit.framework.TestCase;

/**
 * The class <code>BinFileTest</code> contains tests for the class {@link
 * <code>BinFile</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 14/02/11 3:21 PM
 *
 * @author god08d
 *
 * @version $Revision$
 */
public class BinFileTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public BinFileTest(String name) {
		super(name);
	}

	/**
	 * Run the int readInt() method test
	 */
	public void testReadInt() {
		fail("Newly generated method - fix or disable");
		// add test code here
		BinFile fixture = new BinFile();
		int result = fixture.readInt();
		assertTrue(false);
	}

	/**
	 * Run the void writeInt(int) method test
	 */
	public void testWriteInt() {
		fail("Newly generated method - fix or disable");
		// add test code here
		BinFile fixture = new BinFile();
		int value = 0;
		fixture.writeInt(value);
		assertTrue(false);
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = readInt(),writeInt(I)
 * package = au.org.ala.delta.slotfile
 * package.sourceFolder = open-delta/src/test/java
 * superclassType = junit.framework.TestCase
 * testCase = BinFileTest
 * testClassType = BinFile
 */
